<a href="https://colab.research.google.com/github/ManelSoengas/Python_LM/blob/main/Python_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy pandas matplotlib seaborn


In [2]:
# Algebra i matrius
import numpy as np

# Crear una matriu aleatòria de 3x3
matriu = np.random.rand(3,3)
print("Matriu aleatòria:\n", matriu)

# Operacions bàsiques
print("Suma de la matriu:\n", matriu + 2)
print("Producte escalar:\n", matriu * 2)


Matriu aleatòria:
 [[0.20540497 0.29458653 0.87065012]
 [0.26687319 0.45081381 0.90339209]
 [0.00534315 0.15579379 0.01050105]]
Suma de la matriu:
 [[2.20540497 2.29458653 2.87065012]
 [2.26687319 2.45081381 2.90339209]
 [2.00534315 2.15579379 2.01050105]]
Producte escalar:
 [[0.41080995 0.58917305 1.74130025]
 [0.53374637 0.90162762 1.80678418]
 [0.0106863  0.31158759 0.02100209]]


In [4]:
#Exercici
#Crea una matriu 5x5 amb nombres enters aleatoris entre 1 i 100 i calcula la seva mitjana.

import numpy as np

# Crear una matriu aleatòria de 5x5
matriu = np.random.randint(100, size=(5, 5))
print("Matriu aleatòria:\n", matriu)


Matriu aleatòria:
 [[46 44 80 32 40]
 [28 24 83 60 57]
 [12 80 75 32 79]
 [79  2 32  2 47]
 [51 61 20 65 72]]
